# Generated by cucumber-sinatra. (2011-12-01 19:28:03 -0600)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/static_pages.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = StaticPages

class StaticPagesWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  StaticPagesWorld.new
end
